### PR TITLE
NeonDoge Updated

### PR DESCRIPTION
**Pull request by DIQINU**

### CODE REVIEW

**Comment by DIQINU** [comment]
Here is everything for NeonDoge including the logo. Sorry for the confusion. Trying to clean up the commits and having a hell of a time. Thank you!

**Comment by moraswap** [comment]
Please correct the token address, it should not be lowercase.

**Comment by DIQINU** [comment]
Should be fixed @moraswap

**Comment by moraswap** [comment]
Sorry but name of logo folder shoulbe be fixed also.

**Comment by DIQINU** [comment]
The name of the logo folder is also fixed now lol @moraswap thank you!

**Pull request merged**
