### PR TITLE
Update tokenlist.json

### PR DESCRIPTION
**Pull request by limeinvesting**
Adding our token symbol to the Moraswap pair.

### CODE REVIEW

**Comment by moraswap** [comment]
Please upload your logo.

**Comment by limeinvesting** [comment]
shine (200 x 200 px)

**Comment by moraswap** [comment]
I mean you should create a folder named by your token address and upload the logo there: https://github.com/moraswap/tokens/tree/master/blockchains/neon/assets

**Comment by limeinvesting** [comment]
Hello,

I uploaded a folder with the CA and 200x200 logo to neon/assets

I don't see it at the moment, let me know if I did it wrong or if it's only visible after it's merged.

Unfortunately our dev has the opposite schedule than me, so he's always been asleep when I get to checking on the logo and seeing your comments.

Sorry for the hassle, hopefully I did it right this time. If not, I will make sure to have him do it

**Comment by moraswap** [comment]
Cannot see the folder you created in your commit, please check again.

**Pull request merged**
